use crate::domain::autocomplete::{CompletionItem, CompletionKind};

pub struct OptionProvider;

impl OptionProvider {
    pub fn complete(command: &str, token: &str, limit: usize) -> Vec<CompletionItem> {
        let options = known_options(command);
        if options.is_empty() {
            return Vec::new();
        }

        let is_long = token.starts_with("--");
        let prefix = if is_long { token } else { token };

        options
            .iter()
            .filter(|(flag, _)| flag.starts_with(prefix))
            .take(limit)
            .map(|(flag, desc)| CompletionItem {
                label: format!("{flag}  {desc}"),
                insert_text: flag.to_string(),
                kind: CompletionKind::Command,
                description: Some(desc.to_string()),
                score: 90,
            })
            .collect()
    }
}

fn known_options(command: &str) -> &'static [(&'static str, &'static str)] {
    match command {
        "ls" => &[
            ("-l", "long listing format"),
            ("-a", "show hidden files"),
            ("-h", "human-readable sizes"),
            ("-R", "list recursively"),
            ("-t", "sort by modification time"),
            ("-r", "reverse sort order"),
            ("-S", "sort by file size"),
            ("-1", "one file per line"),
            ("-d", "list directories themselves"),
            ("-i", "show inode numbers"),
            ("-n", "numeric uid/gid"),
            ("--all", "show hidden files"),
            ("--human-readable", "human-readable sizes"),
            ("--recursive", "list recursively"),
            ("--sort=time", "sort by time"),
            ("--sort=size", "sort by size"),
            ("--color=auto", "colorize output"),
        ],
        "grep" => &[
            ("-r", "recursive search"),
            ("-i", "ignore case"),
            ("-n", "show line numbers"),
            ("-l", "files with matches only"),
            ("-v", "invert match"),
            ("-c", "count matches"),
            ("-w", "match whole words"),
            ("-E", "extended regex"),
            ("-P", "perl regex"),
            ("-A", "lines after match"),
            ("-B", "lines before match"),
            ("-C", "context lines"),
            ("--include=", "search only matching files"),
            ("--exclude=", "skip matching files"),
            ("--exclude-dir=", "skip directories"),
            ("--color=auto", "highlight matches"),
        ],
        "find" => &[
            ("-name", "match filename pattern"),
            ("-iname", "case-insensitive name"),
            ("-type", "file type (f=file, d=dir)"),
            ("-size", "file size (+10M, -1k)"),
            ("-mtime", "modification time in days"),
            ("-exec", "execute command on results"),
            ("-delete", "delete matching files"),
            ("-maxdepth", "max directory depth"),
            ("-mindepth", "min directory depth"),
            ("-perm", "file permissions"),
            ("-user", "file owner"),
            ("-group", "file group"),
        ],
        "chmod" => &[
            ("-R", "recursive"),
            ("-v", "verbose"),
            ("--recursive", "change files and directories recursively"),
        ],
        "chown" => &[
            ("-R", "recursive"),
            ("-v", "verbose"),
            ("--recursive", "change files and directories recursively"),
        ],
        "cp" => &[
            ("-r", "copy directories recursively"),
            ("-v", "verbose"),
            ("-i", "prompt before overwrite"),
            ("-f", "force overwrite"),
            ("-p", "preserve attributes"),
            ("-a", "archive mode (-dR --preserve=all)"),
            ("--backup", "make backup of each file"),
        ],
        "mv" => &[
            ("-v", "verbose"),
            ("-i", "prompt before overwrite"),
            ("-f", "force overwrite"),
            ("-n", "no overwrite"),
            ("--backup", "make backup of each file"),
        ],
        "rm" => &[
            ("-r", "remove directories recursively"),
            ("-f", "force remove"),
            ("-v", "verbose"),
            ("-i", "prompt before removal"),
            ("--no-preserve-root", "allow removing /"),
        ],
        "mkdir" => &[
            ("-p", "create parent directories"),
            ("-v", "verbose"),
            ("-m", "set permissions mode"),
        ],
        "cat" => &[
            ("-n", "number all lines"),
            ("-b", "number non-blank lines"),
            ("-s", "squeeze blank lines"),
            ("-A", "show all (tabs, endings)"),
        ],
        "tail" => &[
            ("-f", "follow file growth"),
            ("-n", "number of lines"),
            ("-F", "follow with retry"),
            ("--pid=", "terminate after pid dies"),
        ],
        "head" => &[
            ("-n", "number of lines"),
            ("-c", "number of bytes"),
        ],
        "tar" => &[
            ("-c", "create archive"),
            ("-x", "extract archive"),
            ("-z", "gzip compression"),
            ("-j", "bzip2 compression"),
            ("-v", "verbose"),
            ("-f", "archive file name"),
            ("-t", "list archive contents"),
            ("-C", "change directory"),
            ("--exclude=", "exclude pattern"),
        ],
        "curl" => &[
            ("-o", "output to file"),
            ("-O", "save with remote filename"),
            ("-s", "silent mode"),
            ("-S", "show error with silent"),
            ("-L", "follow redirects"),
            ("-v", "verbose"),
            ("-X", "request method (GET, POST...)"),
            ("-H", "add header"),
            ("-d", "POST data"),
            ("-k", "allow insecure SSL"),
            ("-I", "headers only"),
            ("--max-time", "timeout in seconds"),
        ],
        "docker" => &[
            ("ps", "list containers"),
            ("images", "list images"),
            ("run", "run a container"),
            ("exec", "exec into container"),
            ("logs", "view container logs"),
            ("build", "build image"),
            ("pull", "pull image"),
            ("push", "push image"),
            ("stop", "stop container"),
            ("rm", "remove container"),
            ("rmi", "remove image"),
            ("compose", "docker compose"),
        ],
        "systemctl" => &[
            ("start", "start a service"),
            ("stop", "stop a service"),
            ("restart", "restart a service"),
            ("status", "show service status"),
            ("enable", "enable service at boot"),
            ("disable", "disable service at boot"),
            ("reload", "reload service config"),
            ("daemon-reload", "reload systemd config"),
            ("list-units", "list loaded units"),
            ("list-unit-files", "list installed units"),
        ],
        "ssh" => &[
            ("-p", "port number"),
            ("-i", "identity file (private key)"),
            ("-v", "verbose mode"),
            ("-N", "no remote command"),
            ("-L", "local port forwarding"),
            ("-R", "remote port forwarding"),
            ("-D", "dynamic port forwarding"),
            ("-o", "option (StrictHostKeyChecking=no)"),
            ("-q", "quiet mode"),
        ],
        "scp" => &[
            ("-r", "recursive copy"),
            ("-P", "port number"),
            ("-i", "identity file"),
            ("-v", "verbose"),
            ("-C", "compression"),
        ],
        "rsync" => &[
            ("-a", "archive mode"),
            ("-v", "verbose"),
            ("-z", "compress during transfer"),
            ("-P", "show progress + partial"),
            ("--delete", "delete extraneous files"),
            ("--exclude=", "exclude pattern"),
            ("-e", "specify remote shell"),
            ("-n", "dry run"),
        ],
        "ps" => &[
            ("aux", "all processes (BSD style)"),
            ("-ef", "all processes (POSIX)"),
            ("-p", "select by PID"),
            ("-u", "select by user"),
            ("--forest", "show process tree"),
        ],
        "kill" => &[
            ("-9", "SIGKILL (force kill)"),
            ("-15", "SIGTERM (graceful)"),
            ("-l", "list signal names"),
            ("-s", "specify signal"),
        ],
        "du" => &[
            ("-h", "human-readable sizes"),
            ("-s", "summary total only"),
            ("-d", "max depth"),
            ("--max-depth=", "max directory depth"),
        ],
        "df" => &[
            ("-h", "human-readable sizes"),
            ("-T", "show filesystem type"),
            ("-i", "show inode info"),
        ],
        "wget" => &[
            ("-O", "output file"),
            ("-q", "quiet"),
            ("-c", "continue partial download"),
            ("-r", "recursive download"),
            ("--no-check-certificate", "skip SSL verify"),
        ],
        "apt" | "apt-get" => &[
            ("update", "update package list"),
            ("upgrade", "upgrade packages"),
            ("install", "install package"),
            ("remove", "remove package"),
            ("autoremove", "remove unused deps"),
            ("search", "search packages"),
            ("list", "list packages"),
            ("--installed", "show installed only"),
        ],
        "yum" | "dnf" => &[
            ("install", "install package"),
            ("remove", "remove package"),
            ("update", "update packages"),
            ("search", "search packages"),
            ("list", "list packages"),
            ("info", "show package info"),
            ("clean", "clean cache"),
        ],
        "npm" => &[
            ("install", "install packages"),
            ("run", "run script"),
            ("start", "start project"),
            ("test", "run tests"),
            ("build", "build project"),
            ("init", "create package.json"),
            ("publish", "publish package"),
            ("--save-dev", "save as devDependency"),
            ("-g", "global install"),
        ],
        "cargo" => &[
            ("build", "compile the project"),
            ("run", "build and run"),
            ("test", "run tests"),
            ("check", "check without building"),
            ("clippy", "run linter"),
            ("fmt", "format code"),
            ("add", "add dependency"),
            ("--release", "release profile"),
        ],
        "pip" | "pip3" => &[
            ("install", "install package"),
            ("uninstall", "remove package"),
            ("freeze", "output installed packages"),
            ("list", "list installed packages"),
            ("show", "show package info"),
            ("--upgrade", "upgrade package"),
            ("-r", "install from requirements"),
        ],
        _ => &[],
    }
}
